In [1]:
import os
import pandas as pd

In [22]:
def filter(airport):
    airport = airport.rename(columns={'Destination Airport': 'Destination_Airport'})
    Destination_booleans = []
    for place in airport.Destination_Airport:
        if place == "SFO":
            Destination_booleans.append(True)
        elif place == "LAX":
            Destination_booleans.append(True)
        elif place == "DEN":
            Destination_booleans.append(True)
        elif place == "LAS":
            Destination_booleans.append(True)
        elif place == "PDX":
            Destination_booleans.append(True)
        elif place == "SEA":
            Destination_booleans.append(True)
        elif place == "DFW":
            Destination_booleans.append(True)
        elif place == "MCO":
            Destination_booleans.append(True)
        elif place == "ORD":
            Destination_booleans.append(True)
        elif place == "JFK":
            Destination_booleans.append(True)
        elif place == "ATL":
            Destination_booleans.append(True)
        else:
            Destination_booleans.append(False)
    is_long = pd.Series(Destination_booleans)
    airport = airport[is_long]

In [20]:
ATL1 = pd.read_csv("Resources/CSV/American/ATL.csv", skiprows=7)[:-2]
ATL1["Origin Airport"] = "ATL"

# filter(ATL1)

# DEN1 = pd.read_csv("Resources/CSV/American/DEN.csv", skiprows=7)[:-2]
# DEN1["Origin Airport"] = "DEN"
# DFW1 = pd.read_csv("Resources/CSV/American/DFW.csv", skiprows=7)[:-2]
# DFW1["Origin Airport"] = "DFW"
# JFK1 = pd.read_csv("Resources/CSV/American/JFK.csv", skiprows=7)[:-2]
# JFK1["Origin Airport"] = "JFK"
# LAS1 = pd.read_csv("Resources/CSV/American/LAS.csv", skiprows=7)[:-2]
# LAS1["Origin Airport"] = "LAS"
# LAX1 = pd.read_csv("Resources/CSV/American/LAX.csv", skiprows=7)[:-2]
# LAX1["Origin Airport"] = "LAX"
# MCO1 = pd.read_csv("Resources/CSV/American/MCO.csv", skiprows=7)[:-2]
# MCO1["Origin Airport"] = "MCO"
# ORD1 = pd.read_csv("Resources/CSV/American/ORD.csv", skiprows=7)[:-2]
# ORD1["Origin Airport"] = "ORD"
# PDX1 = pd.read_csv("Resources/CSV/American/PDX.csv", skiprows=7)[:-2]
# PDX1["Origin Airport"] = "PDX"
# SEA1 = pd.read_csv("Resources/CSV/American/SEA.csv", skiprows=7)[:-2]
# SEA1["Origin Airport"] = "SEA"
# SFO1 = pd.read_csv("Resources/CSV/American/SFO.csv", skiprows=7)[:-2]
# SFO1["Origin Airport"] = "SFO"
ATL1

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination_Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Origin Airport
0,AA,01/01/2015,17.0,N019AA,MIA,07:00,06:56,112.0,106.0,-4.0,07:11,15.0,0.0,0.0,0.0,0.0,0.0,ATL
1,AA,01/01/2015,125.0,N585AA,DFW,17:55,17:54,155.0,135.0,-1.0,18:08,14.0,0.0,0.0,0.0,0.0,0.0,ATL
2,AA,01/01/2015,194.0,N025AA,DFW,15:25,15:34,145.0,149.0,9.0,15:48,14.0,0.0,0.0,0.0,0.0,0.0,ATL
3,AA,01/01/2015,232.0,N599AA,DFW,19:00,18:58,150.0,177.0,-2.0,19:15,17.0,0.0,0.0,25.0,0.0,0.0,ATL
4,AA,01/01/2015,276.0,N4YCAA,DFW,20:15,20:29,145.0,189.0,14.0,21:40,71.0,0.0,0.0,44.0,0.0,14.0,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54698,AA,12/31/2018,2328.0,N830NN,LAX,06:35,06:30,322.0,317.0,-5.0,06:44,14.0,0.0,0.0,0.0,0.0,0.0,ATL
54699,AA,12/31/2018,2344.0,N942NN,MIA,07:28,07:24,121.0,114.0,-4.0,07:39,15.0,0.0,0.0,0.0,0.0,0.0,ATL
54700,AA,12/31/2018,2477.0,N849NN,MIA,11:49,11:45,116.0,116.0,-4.0,12:04,19.0,0.0,0.0,0.0,0.0,0.0,ATL
54701,AA,12/31/2018,2619.0,N966NN,DFW,09:29,09:24,156.0,149.0,-5.0,09:39,15.0,0.0,0.0,0.0,0.0,0.0,ATL
54702,AA,12/31/2018,2717.0,N90024,MIA,09:12,09:08,128.0,117.0,-4.0,09:18,10.0,0.0,0.0,0.0,0.0,0.0,ATL

In [23]:
filter(ATL1)
ATL1

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination_Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Origin Airport
0,AA,01/01/2015,17.0,N019AA,MIA,07:00,06:56,112.0,106.0,-4.0,07:11,15.0,0.0,0.0,0.0,0.0,0.0,ATL
1,AA,01/01/2015,125.0,N585AA,DFW,17:55,17:54,155.0,135.0,-1.0,18:08,14.0,0.0,0.0,0.0,0.0,0.0,ATL
2,AA,01/01/2015,194.0,N025AA,DFW,15:25,15:34,145.0,149.0,9.0,15:48,14.0,0.0,0.0,0.0,0.0,0.0,ATL
3,AA,01/01/2015,232.0,N599AA,DFW,19:00,18:58,150.0,177.0,-2.0,19:15,17.0,0.0,0.0,25.0,0.0,0.0,ATL
4,AA,01/01/2015,276.0,N4YCAA,DFW,20:15,20:29,145.0,189.0,14.0,21:40,71.0,0.0,0.0,44.0,0.0,14.0,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54698,AA,12/31/2018,2328.0,N830NN,LAX,06:35,06:30,322.0,317.0,-5.0,06:44,14.0,0.0,0.0,0.0,0.0,0.0,ATL
54699,AA,12/31/2018,2344.0,N942NN,MIA,07:28,07:24,121.0,114.0,-4.0,07:39,15.0,0.0,0.0,0.0,0.0,0.0,ATL
54700,AA,12/31/2018,2477.0,N849NN,MIA,11:49,11:45,116.0,116.0,-4.0,12:04,19.0,0.0,0.0,0.0,0.0,0.0,ATL
54701,AA,12/31/2018,2619.0,N966NN,DFW,09:29,09:24,156.0,149.0,-5.0,09:39,15.0,0.0,0.0,0.0,0.0,0.0,ATL
54702,AA,12/31/2018,2717.0,N90024,MIA,09:12,09:08,128.0,117.0,-4.0,09:18,10.0,0.0,0.0,0.0,0.0,0.0,ATL

In [ ]:
concat = pd.concat([ATL1, DEN1, DFW1, JFK1, LAS1, LAX1, MCO1, ORD1, PDX1, SEA1, SFO1])
concat['Carrier Code'] = "American Airlines"
filter(concat)
concat.set_index("Origin Airport")

In [ ]:
ATL2 = pd.read_csv("Resources/CSV/Alaska/ATL.csv", skiprows=7)[:-2]
ATL2["Origin Airport"] = "ATL"
DEN2 = pd.read_csv("Resources/CSV/Alaska/DEN.csv", skiprows=7)[:-2]
DEN2["Origin Airport"] = "DEN"
DFW2 = pd.read_csv("Resources/CSV/Alaska/DFW.csv", skiprows=7)[:-2]
DFW2["Origin Airport"] = "DFW"
JFK2 = pd.read_csv("Resources/CSV/Alaska/JFK.csv", skiprows=7)[:-2]
JFK2["Origin Airport"] = "JFK"
LAS2 = pd.read_csv("Resources/CSV/Alaska/LAS.csv", skiprows=7)[:-2]
LAS2["Origin Airport"] = "LAS"
LAX2 = pd.read_csv("Resources/CSV/Alaska/LAX.csv", skiprows=7)[:-2]
LAX2["Origin Airport"] = "LAX"
MCO2 = pd.read_csv("Resources/CSV/Alaska/MCO.csv", skiprows=7)[:-2]
MCO2["Origin Airport"] = "MCO"
ORD2 = pd.read_csv("Resources/CSV/Alaska/ORD.csv", skiprows=7)[:-2]
ORD2["Origin Airport"] = "ORD"
PDX2 = pd.read_csv("Resources/CSV/Alaska/PDX.csv", skiprows=7)[:-2]
PDX2["Origin Airport"] = "PDX"
SEA2 = pd.read_csv("Resources/CSV/Alaska/SEA.csv", skiprows=7)[:-2]
SEA2["Origin Airport"] = "SEA"
SFO2 = pd.read_csv("Resources/CSV/Alaska/SFO.csv", skiprows=7)[:-2]
SFO2["Origin Airport"] = "SFO"

In [ ]:
concat2 = pd.concat([ATL2, DEN2, DFW2, JFK2, LAS2, LAX2, MCO2, ORD2, PDX2, SEA2, SFO2]).set_index("Origin Airport")
concat2['Carrier Code'] = "Alaska Airlines"
concat2

In [ ]:
ult_concat = pd.concat([concat, concat2])
ult_concat